theme: minima
title: _Arthur Andrade
url: https://arthurandrade-rj.github.io
baseurl: ""
description: "_Arthur Andrade Homepage"
keywords: "Chandan Singh, Machine Learning, Berkeley, Interpretability, Explainability"
collections:
 research_ovws:
    name: research_ovws
    output: true
 blog:
    name: blog
    output: true
 notes:
    name: Notes
    documentation: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
    output: true
 timeline_blurbs:
    name: timeline_blurbs
    output: true
markdown: kramdown
highlighter: rouge
exclude: ["Rakefile", "LICENSE", "readme.md"]

owner:
  name: Arthur Andrade
  avatar: bio-photo.jpg
  bio: "23 anos, Graduando em Engenharia de Produção pela UERJ, analista financeiro na TIM."
  email: arthurandrade.rj@hotmail.com
  # Do not include the @ symbol in your Twitter username
  linkedin: arthurandraderj
  github: arthurandrade-rj

footer-links:
  email: arthurandrade.rj@hotmail.com
  linkedin: arthurandraderj

